version: "3"

services: 
  app-be:
    image: dalmanza9119/web-app-zemoga-test
    ports:
      - "8087:8080"
 #  app-be-consumer:
 #   image: dalmanza9119/web-app-zemoga-test
 #   ports:
 #     - "8081:8080"
  app-fe:
    image: dalmanza9119/web-app-zemoga-fe-test:latest
    ports: 
      - "4200:4200"
